[tool.poetry]
name = "dpsprep"
version = "2.0.0"
description = "A DjVu to PDF convertor with the ability to preserve bookmarks and text layers"
authors = ["Kevin Arthur Schiff Croker", "Ianis Vasilev"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
pypdf = "^3.8.1"
click = "^8.1.3"
python-djvulibre = "^0.8.8"
pillow = "^9.5.0"
reportlab = "^3.6.13"
loguru = "^0.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
ruff = "^0.0.263"
mypy = "^1.2.0"
types-pillow = "^9.5.0.2"
pytest-image-diff = "^0.0.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["E501"]

[[tool.mypy.overrides]]
module = [
  "djvu.*",
  "loguru.*",
  "pypdf.*",
  "reportlab.*"
]
ignore_missing_imports = true
